services:
  csharp-dev:
    build:
      context: .
      args:
        - USER=${USER:-user} # # Your User Name
        - USER_ID=${USER_ID:-1000} # Your User ID
        - GROUP_ID=${GROUP_ID:-1000} # Your GROUP ID
        - DOTNET_VERSION=${DOTNET_VERSION:-10.0} # dotnet version
        - DEBIAN_VERSION_NAME=${DEBIAN_VERSION_NAME:-stable} # debian code name
    image: csharp-dev:debian
    container_name: csharp-dev
    volumes:
      - type: bind
        source: ../
        target: /WORKDIR
    tty: true
    command: bash
